My\RecipesBundle\Entity\Author:
    type: entity
    repositoryClass: My\RecipesBundle\Repository\AuthorRepository
    table: authors
    oneToMany:
        recipes:
          targetEntity: Recipe
          mappedBy: author
          fetch: EXTRA_LAZY
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255

        surname:
            type: string
            length: 255