my_recipes_recipe_create:
    pattern:  /recipes/create
    defaults: { _controller: MyRecipesBundle:Recipe:create }

my_recipes_recipe_show:
    pattern:  /recipes/{id}
    defaults: { _controller: MyRecipesBundle:Recipe:show }

my_recipes_author_create:
    pattern:  /authors/create
    defaults: { _controller: MyRecipesBundle:Author:create }

my_recipes_author_show:
    pattern:  /authors/{id}
    defaults: { _controller: MyRecipesBundle:Author:show }

top_chefs:
    pattern:  /top-chefs
    defaults: { _controller: MyRecipesBundle:Recipe:topChefs }
