parameters:
#    my_recipes.example.class: My\RecipesBundle\Example

services:
    my.twig.recipes_extension:
        class: My\RecipesBundle\Twig\RecipesExtension
        tags:
            - { name: twig.extension }