parameters:
#    my_recipes.example.class: My\RecipesBundle\Example

services:
    my.twig.recipes_extension:
        class: My\RecipesBundle\Twig\RecipesExtension
        tags:
            - { name: twig.extension }

    my_recipes.form.type.difficulty:
        class: My\RecipesBundle\Form\Type\DifficultyType
        tags:
            - { name: form.type, alias: difficulty }

    my_recipes.form.type.author:
        class: My\RecipesBundle\Form\Type\AuthorType
        tags:
            - { name: form.type, alias: author }